### ISSUE TITLE
Does not seem to work inside List View

### ISSUE THREAD

**Issue by winstonschen** [Whiffer/SampleSwiftDataTransferrable#1]
Hi,
Thanks for trying to tackle this problem! I need this functionality and struggled a lot to get it to work.
I tried your Swift Package and it didn't work. The row in the list drags but I couldn't get it to accept drop. Then I tried your sample (had to change the code a bit to get the toolbar to show up), but again, I got the same result.
Are you still working on this, or have you abandon it? Again, I would love to get this to work but now I'm just resorting to context menu rather than the more elegant drag and drop.
Thanks again,
Winston.

**Comment by Whiffer** [comment]
Hi, I have been planning to do more work with this package, but currently have higher priority projects.  I will look into it when I am able.  On what platform are you having your issue?  I have only tried to use it on macOS so far.  I definitely want to explore using it on iPadOS and maybe iOS.   Another thing to look into is the placement of your .dropDestination view modifier.  Also, setting breakpoints in the .dropDestination closures can help locate the reason the drop is not targeting.
Thanks.
Chuck

**Comment by Whiffer** [comment]
I have spent some time looking at this.  See my comments on the issue posted in the package's repo: https://github.com/Whiffer/swiftdata-transferrable

**Comment by Whiffer** [comment]
Ignore my last two comments. I believe that the fundamental reason for the issue you posted is likely a bug in Apple's handling of drops into SwiftUI List's (at least with the Transferrable versions of the view modifiers).  There is a lot of discussion on this. Here is one post:  https://stackoverflow.com/questions/69931818/drag-and-drop-on-a-list-row-in-swiftui
I will file a Feedback on this and post the number here in case this is important to anyone else.  Thanks.

**Comment by Whiffer** [comment]
Not sure whether this is a bug or just a design deficiency.  In any case, I filed a suggestion Feedback with Apple for iOS Drag and Drop. Feedback number is FB13648218 with title: "Unable to make a SwiftUI List Row a drag and drop target".  Since the squeaky wheel gets the grease, if you want this, I suggest piling on with more Feedbacks for the same thing.  One of the points I made was that this works on macOS and they should strive to make this work on iOS as well for consistency with Multiplatform Apps.

**Comment by Whiffer** [comment]
I have been trying to create a suitable workaround in my App for not being able to drag a row from a List onto another row in the same List on iOS (it does work on macOS).  For what it's worth, I have noticed that it is possible on iOS to drag a row from one List onto a row in a different List in the same View.
